### PR TITLE
Try to fix the PyPy2 job on TravisCI

### PR DESCRIPTION
**Pull request by icemac**
It seems to use a too old OpenSSL version.

### CODE REVIEW

**Comment by dataflake** [comment]
I am seriously confused why that pip invocation fails under pypy2 but not under Python 2.7. That makes no sense.

**Review by dataflake — APPROVED** [review]
After looking at the Travis log and comparing pypy and Python 2.7 runs my best guess is that the precompiled pypy they load is linked against OpenSSL 1.0.2 but their Python 2.7 is not. I would consider that a breakage on their end. The workaround looks fine.

**Review by mgedmin — APPROVED** [review]
This works, but AFAIU cryptography plans to drop the CRYPTOGRAPHY_ALLOW_OPENSSL_102 workaround in the future, so we might as well jump into the present by doing

    dist: focal

and changing `pypy` to `pypy2`.

**Comment by dataflake** [comment]
> This works, but AFAIU cryptography plans to drop the CRYPTOGRAPHY_ALLOW_OPENSSL_102 workaround in the future, so we might as well jump into the present by doing
> 
> ```
> dist: focal
> ```
> 
> and changing `pypy` to `pypy2`.

I knew there had to be a better way...  I'm not familiar with Ubuntu naming, so focal is the successor of xenial?

**Comment by mgedmin** [comment]
> I knew there had to be a better way... I'm not familiar with Ubuntu naming, so focal is the successor of xenial?

Ubuntu 16.04 LTS is xenial, released in March 2016, so a bit dated by now.

Ubuntu 18.04 LTS is bionic

Ubuntu 20.04 LTS is focal, so not a _direct_ successor, but a successor.

(There were also non-LTS releases between these, named in alphabetical order: xenial, yakkety, zesty, artful, bionic, cosmic, disco eoan, focal.)

**Review by mgedmin — APPROVED** [review]

**Comment by mgedmin** [comment]
Welp, the tests fail in a really bizarre way:

```
=================================== FAILURES ===================================
___________________________ testLongPassword[CRYPT] ____________________________
schema_id = 'CRYPT'
    @pytest.mark.parametrize('schema_id', AuthEncoding.listSchemes())
    def testLongPassword(schema_id):
        pw = u'Pw' * 2000
        enc = AuthEncoding.pw_encrypt(pw, schema_id)
>       assert AuthEncoding.pw_validate(enc, pw)
E       AssertionError: assert False
E        +  where False = <function pw_validate at 0x7ff621bb0050>(b'{CRYPT}*0', 'PwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwP...PwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPwPw')
E        +    where <function pw_validate at 0x7ff621bb0050> = AuthEncoding.pw_validate
src/AuthEncoding/tests/test_AuthEncoding.py:67: AssertionError
```

**Comment by dataflake** [comment]
That looks like a misbehaving crypt library?

**Comment by dataflake** [comment]
The tests pass now with Michael's original code. I propose merging this because the issues appear to come from crypt library issues on those newer platforms and from Travis' own precompiled Python interpreters. They don't show issues with the code itself.

**Review by mgedmin — APPROVED** [review]
:+1:

**Comment by icemac** [comment]
Thank you for investigating this issue.

**Pull request merged**
